### PR TITLE
Revert "Fixed middle click (I think)"

### PR DESCRIPTION
**Pull request by tluck**
Reverts tluck/OS-X-Voodoo-PS2-Controller#3

### CODE REVIEW

**Comment by jakibaki** [comment]
What's wrong with it?

**Comment by tluck** [comment]
nothing! i made a few minor changes
i used your logic to implement for both T420/X220 and T460.
please test on your box.

**Comment by jakibaki** [comment]
Your implementation seems to result in the middle click only registering after moving the mouse when the touchpad is disabled (x220)

**Comment by tluck** [comment]
hmm thats odd. its seems i only removed a 2nd dispatch call on say 2nd time through after middle button release

so for never scrolled situation, after middle button is released.
combinedButtons = 0
pressedLast = true (1)
everScrolled = false (0)

this results in:
calls dispatch with 4
and
calls dispatch with 0

```
        if (everScrolled == false && pressedLast == 1 && combinedButtons != 4)
        {
            dispatchRelativePointerEventX(dx, -dy, 4, now_abs);
        }
        if (combinedButtons == 4){
            pressedLast = 1;
        }else{
            pressedLast = 0;
            everScrolled = 0;
            dispatchRelativePointerEventX(dx, -dy, combinedButtons, now_abs);
        }


```
vs

```
        if (mousemiddlescroll && combinedButtons == 4)
            middleButtonPressed = true;
        else
        {
            if( middleButtonPressed )
            {
                if(!everScrolled) dispatchRelativePointerEventX(dx, -dy, 4, now_abs);
            }
            else
            {
                dispatchRelativePointerEventX(dx, -dy, combinedButtons, now_abs);
            }
            middleButtonPressed = false;
            everScrolled = false;
        }

```
which only calls dispatch with 4 

so does the 220 need the 2nd dispatch with 0 ?
is mousemiddlescroll true for your config?

**Comment by jakibaki** [comment]
I just use the default config so I think it is true (not entirely sure).

**Comment by tluck** [comment]
ok yeah is true by default.
i wonder if this code works for you?

```
        if (mousemiddlescroll && combinedButtons == 4)
            middleButtonPressed = true;
        else
        {
            if( middleButtonPressed && !everScrolled) dispatchRelativePointerEventX(dx, -dy, 4, now_abs);
            dispatchRelativePointerEventX(dx, -dy, combinedButtons, now_abs);
            middleButtonPressed = false;
            everScrolled = false;
        }

```

**Comment by jakibaki** [comment]
Yes it works perfectly fine :)

**Comment by tluck** [comment]
ok - oddly the 220 needs the 2nd call? 
with the T420 and the T460 - they dont!

... i will retest with this this new snippet. a 2nd call won't hurt much!

thanks again

**Comment by jakibaki** [comment]
no problem :D

**Pull request closed without merging**
